version: "3"
services:
  price-scraper:
    container_name: price-scraper
    build:
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=testtest
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    ports:
      - "8086:8086"
volumes:
  influxdb2:
