services:
  webstore-scraper:
    container_name: webstore-scraper
    build:
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
      RUN_STARTUP_UPDATE: ${RUN_STARTUP_UPDATE}
    volumes:
      - ./logs:/logs

  price-api:
    container_name: price-api
    build:
      context: ../google-shopping-history
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: andri
      MONGO_INITDB_ROOT_PASSWORD: MongoMasterMikael

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: andri
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoAdminMatti
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
