services:
  price-scraper:
    container_name: price-scraper
    build:
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - IMPORT_INFLUXDB=${IMPORT_INFLUXDB}
      - RUN_STARTUP_UPDATE=${RUN_STARTUP_UPDATE}

  price-api:
    container_name: price-api
    build:
      context: ../google-shopping-history
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: andri
      MONGO_INITDB_ROOT_PASSWORD: MongoMasterMikael

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: andri
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoAdminMatti
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
